providers:
  - airtap-sauce
  - airtap-default

browsers:
  - name: chrome
  - name: firefox
  # https://github.com/airtap/sauce/issues/11
  # - name: safari
  #   version: 12..latest
  - name: ios_saf
    version: 12..latest
  - name: chrome for android
    version: 6..latest
  - name: msedge

presets:
  local:
    browsers:
      - name: default
