browsers:
  - name: chrome
    version: latest
    platform: Windows 10
  - name: firefox
    version: latest
    platform: Windows 10
  - name: iphone
    version: '9.0'
  - name: android
    version: '6.0'
  - name: microsoftedge
    version: latest
