sudo: false
language: node_js

matrix:
  fast_finish: true
  include:
  - node_js: 10
    env: CMD=test
  - node_js: 12
    env: CMD=test
  - node_js: 14
    env: CMD=test
  - node_js: stable
    env: CMD=test-browsers
    addons:
      hosts:
        - airtap.local

before_script: git fetch --tags

script:
  - DEBUG=airtap:* npm run $CMD

after_success: npm run coverage

notifications:
  email: false
